[package]
name = "osmflat"
version = "0.1.0"
authors = ["boxdot <d@zerovolt.org>"]

[dependencies]
bytes = "0.4"
docopt = "1.0"
flatdata = "0.1.3"
prost = "0.3"
prost-derive = "0.3"
prost-types = "0.3"
serde = "1.0"
serde_derive = "1.0"
byteorder = "1.2"
flate2 = "1.0"
failure = "0.1"
colored = "1.6"
itertools = "0.7"

[build-dependencies]
prost-build = "0.3"

[dev-dependencies]
proptest = "0.6.0"
png = "0.12"
bresenham = "0.1"

[[bin]]
name = "osmflatc"
path = "src/main.rs"

[[example]]
name = "render"
