[package]
name = "osmflat"
version = "0.1.0"
authors = ["boxdot <d@zerovolt.org>"]
license = "MIT/Apache-2.0"
description = "Flat OpenStreetMap (OSM) data format with very efficient random access pattern through memory mapped files."
repository = "https://github.com/boxdot/osmflat-rs"
keywords = ["serialization", "osm", "openstreetmap", "flatdata"]
categories = ["encoding"]
readme = "README.md"

[dependencies]
byteorder = "1.2"
bytes = "0.4"
colored = "1.6"
docopt = "1.0"
failure = "0.1"
flatdata = "0.1.3"
flate2 = "1.0"
itertools = "0.7"
log = "0.4"
pbr = "1.0"
prost = "0.3"
prost-derive = "0.3"
prost-types = "0.3"
serde = "1.0"
serde_derive = "1.0"
stderrlog = "0.4"

[build-dependencies]
prost-build = "0.3"

[dev-dependencies]
proptest = "0.6.0"
png = "0.12"
bresenham = "0.1"
svg = "0.5"
haversine = "0.2"
rayon = "1.0"

[[bin]]
name = "osmflatc"
path = "src/main.rs"

[[example]]
name = "render"

[[example]]
name = "svg"