[package]
name = "osmflat"
version = "0.1.0"
authors = [
    "boxdot <d@zerovolt.org>",
    "Christian Vetter <veaac.fdirct@gmail.com>",
    "Gabriel FÃ©ron <feron.gabriel@gmail.com>"
]
license = "MIT/Apache-2.0"
description = "OpenStreetMap (OSM) data format providing an efficient random data access through memory mapped files."
repository = "https://github.com/boxdot/osmflat-rs"
keywords = ["serialization", "osm", "openstreetmap", "flatdata"]
categories = ["encoding"]
readme = "README.md"
edition = "2018"

[dependencies]
flatdata = { git = "https://github.com/heremaps/flatdata", rev = "71a2e93" }

[dev-dependencies]
itertools = "0.8.2"
png = "0.15.3"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
smallvec = "1.2.0"
structopt = "0.3.9"
svg = "0.6.0"
